alias php74 '/opt/homebrew/opt/php@7.4/bin/php'
alias composer74 '/opt/homebrew/opt/php@7.4/bin/php /opt/homebrew/bin/composer'
alias php56 '/opt/homebrew/opt/php@5.6/bin/php'
alias composer56 '/opt/homebrew/opt/php@5.6/bin/php /opt/homebrew/bin/composer'
alias php83 '/opt/homebrew/opt/php@8.3/bin/php'
alias composer83 '/opt/homebrew/opt/php@8.3/bin/php /opt/homebrew/bin/composer'
