add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_status]
format = '[$all_status$ahead_behind ]($style)'
conflicted = '=$count '
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇕$count '
up_to_date = '✓'
untracked = '[?$count ](white)'
stashed = '$$count '
modified = '!$count '
staged = '[++\($count\) ](green)'
renamed = '»$count '
deleted = '✘$count '
