bind \e\[106\;9u "_fzf_find $HOME"
bind \e\[108\;9u "_fzf_find_search '/Users/mireknguyen/Library/Mobile Documents/com~apple~CloudDocs/notes/programming/'"
bind \e\[106\;10u "_fzf_find --noignorefile"
bind \e\[108\;10u "_fzf_find_search"
bind \e\[105\;9u "cheat-fzf"
bind \e\[111\;9u "switch_tabs"
bind \e\[117\;9u "extract_links '/Users/mireknguyen/Library/Mobile Documents/com~apple~CloudDocs/notes/other/websites.md'"
