bind \e\[106\;9u "_fzf_find $HOME"
bind \e\[108\;9u "_fzf_find_search '$HOME/.local/mount/onedrive/notes/programming/'"
bind \e\[106\;10u "_fzf_find --noignorefile"
# bind \e\[108\;10u "_fzf_find_search"
bind \e\[107\;9u "_fzf_find_search"
