
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- The config is split by topic, following the wiki's advice. Each file is
-- in hyprland/ and required as hyprland.<name> (~/.config/hypr is on
-- package.path).

require("hyprland.monitors")
require("hyprland.autostart")
require("hyprland.env")
require("hyprland.permissions")
require("hyprland.appearance")
require("hyprland.misc")
require("hyprland.input")
require("hyprland.keybinds")
require("hyprland.rules")
require("hymission")            -- Mission Control on F3 (hymission/init.lua)
