hide_display_names= true
library_tabs=["tracks", "playlists"]

[keybindings]
"[" = "focus queue"
"]" = "focus library"
"?" = "focus search"
"Space" = "playpause"
"Escape" = "back"
";" = "play"
"'" = "queue"
"ยง" = "help"
"+" = "volup 5"
"-" = "voldown 5"
"s" = "save"
"S" = "add"
"." = "seek +10s"
"," = "seek -10s"
"g" = "move top"
"G" = "move bottom"

[theme]
# primary = "#ebdbb2"
# secondary = "#928374"
# title = "#fabd2f"
playing = "#98971a"
playing_selected = "#b8bb26"
# playing_bg = "black"
# highlight = "#fe8019"
highlight_bg = "#303030"
# error = "#fb4934"
statusbar = "#928374"
statusbar_progress = "#b8bb26"
# statusbar_bg = "black"
# cmdline = "#83a598"
# cmdline_cursor = "#fe8019"
# cmdline_bg = "black"
# search_match = "#fabd2f"
