hide_display_names= true
library_tabs=["tracks", "albums", "artists", "playlists"]
[keybindings]
"[" = "focus queue"
"]" = "focus library"
"?" = "focus search"
"Space" = "playpause"
"Escape" = "back"
";" = "play"
"'" = "queue"
"ยง" = "help"
"+" = "volup 5"
"-" = "voldown 5"

