hide_display_names= true
library_tabs=["tracks", "playlists"]

[keybindings]
"[" = "focus queue"
"]" = "focus library"
"?" = "focus search"
"Space" = "playpause"
"Escape" = "back"
";" = "play"
"'" = "queue"
"ยง" = "help"
"+" = "volup 5"
"-" = "voldown 5"
"s" = "save"
"." = "seek +10s"
"," = "seek -10s"
"g" = "move top"
"G" = "move bottom"
